<footer>
    <div class="footercontainer">
        <div><a href="https://github.com/106278803/WebTech_A1" target="_blank">GitHub Link</a></div>
        <div><a href="https://webtechthree.atlassian.net/jira/software/projects/WTA/summary?atlOrigin=eyJpIjoiMjNmNjIyY2NjZDc1NDRlZDhhMTFiNjBiYzk4MWRmNGYiLCJwIjoiaiJ9" target="_blank">Jira Board</a></div>
        <div><a href="mailto:106278803@student.swin.edu.au">Email</a></div>
    </div>
</footer>