
<nav>
    <div class="navcontainer center">
        <div><a href="index.php"> Home Page</a></div>
        <div><a href="about.php"> About Page</a></div>
        <div><a href="jobs.php"> Jobs Page</a></div>
        <div><a href="apply.php"> Apply Page</a></div>
        <div><form><input type="text" aria-label="Search the site" placeholder="Search jobs..."></div>
        <button>Search</button></form>
    </div>
</nav>