<nav>
    <div class="navcontainer center">
        <div><a href="index.php"> Home Page</a></div>
        <div><a href="about.php"> About Page</a></div>
        <div><a href="jobs.php"> Jobs Page</a></div>
        <div><a href="apply.php"> Apply Page</a></div>
        <form>
            <div>
                <input type="text" aria-label="Search the site" placeholder="Search site...">
                <button>Search</button>
            </div>
        </form>
    </div>
</nav>